### PR TITLE
Feature/copier

### LINKED ISSUE #6: Use ruff
## Description

Use ruff for linting and formatting.

### LINKED ISSUE #7: Template supporting updates
## Description

Use a template that supports updating project when template updates. Copier is a good solution. However, I can't find a good way of using GH templates with copier.

### PR DESCRIPTION
**Pull request by mgcth**
## Description

Use copier for python templates instead of GitHub templates. Copier supports updating a project when a template is updated.

- [x] Use copier
- [x] Replace black and flake8 with ruff

### CODE REVIEW

**Review by docNord — COMMENTED** [review]
There are a lot of checks not passing, seemingly because of missing pyproject.toml file. Is this something you plan to address?

**Comment by docNord** [comment]
Remove flake8 test and move to ruff in the lint check?

**Comment by mgcth** [comment]
It's pulling from main where we don't have ruff.

**Review by docNord — DISMISSED** [review]

**Comment by docNord** [comment]
Nice work!

**Comment by mgcth** [comment]
Ok, I think we are done now.

**Review by docNord — APPROVED** [review]
Nice! 🥳

**Pull request merged**
